### ISSUE TITLE
Runtimes folder is not copied during publish-process on .NET Framework

### ISSUE THREAD

**Issue by mrblumi** [HakanL/WkHtmlToPdf-DotNet#39] opened 2021-06-07 15:26 UTC
Publishing .NET Framework (4.8) Projects does not copy runtimes directory to target location.
The problem occures with new csproj-format (i.e. console app) as well as with old csproj-format (i.e. asp.net application)...

Steps to reproduce for first example:
- `dotnet new console -n Test -o ./`
- changing target framework to net48 in csproj file
- `dotnet add package Haukcode.WkHtmlToPdfDotNet --version 1.5.8`
- `dotnet publish --configuration=Release`

I have not tried to get a minimum example for legacy csproj format since I think it s the same problem with both formats...

**Comment by mrblumi** [comment] 2021-06-07 15:52
Okey, I managed to get a hacky fix for this in asp.net framework project by adding these lines at the bottom of the publish profile

```
<Target Name="CustomCollectFiles">
    <ItemGroup>
      <_CustomFiles Include="$(SolutionDir)\packages\Haukcode.WkHtmlToPdfDotNet.1.5.8\runtimes\win-*\**\*" />
      <FilesForPackagingFromProject Include="%(_CustomFiles.Identity)">
        <DestinationRelativePath>bin\runtimes\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>
  
  <PropertyGroup>
    <CopyAllFilesToSingleFolderForPackageDependsOn>
      CustomCollectFiles;
      $(CopyAllFilesToSingleFolderForPackageDependsOn);
    </CopyAllFilesToSingleFolderForPackageDependsOn>

    <CopyAllFilesToSingleFolderForMsdeployDependsOn>
      CustomCollectFiles;
      $(CopyAllFilesToSingleFolderForMsdeployDependsOn);
    </CopyAllFilesToSingleFolderForMsdeployDependsOn>
  </PropertyGroup>
```

But it is still a nasty because one has to think about manually fixing package version while upgrading nuget dependency.

**Comment by mrblumi** [comment] 2021-06-07 18:20
It s not realy a fix, it is an ugly hack appended inside the .pubxml file of our ASP.NET project which copies the required files into the publish folder, because otherwise we would forget to publish them manually every now and then ;) 

I try to give you a working minimum example tomorrow

**Comment by mrblumi** [comment] 2021-06-08 13:19
Created a minimal ASP.NET API and installed Haukcode.WkHtmlToPdfDotNET nuget package and finally added two visual studio publish profiles (one with above additions, one without)
[Demo](https://github.com/mrblumi/WkHtmlToPdfMinimalAspNet)

First I tried to get something working like this inside csproj file, but as I am not that familiar with legacy framework build techniques I had no success. Maybe this can be a starting point for a real fix...

**Comment by mrblumi** [comment] 2021-06-08 13:28
I 100% agree!!!

**Comment by horizondave** [comment] 2021-10-04 16:22
I'm not an expert in this by any means, but it looks like there are a couple of options for getting the nuget working properly with .net framework.
1. Multi-target using `<TargetFramework>`
2. Use the "lib" directory to host windows versions of the DLLs specifically for .net platform.

https://stackoverflow.com/questions/52397501/nuget-references-to-assemblies-in-runtimes-folder-not-added

**Comment by horizondave** [comment] 2021-10-05 11:39
I've got this working on a local nuget feed OK.  Sent a pull request for you to review.

**Comment by mrblumi** [comment] 2021-10-05 21:06
I can test this tomorrow afternoon :)

**Comment by horizondave** [comment] 2021-10-06 08:17
Version 1.5.59 works fine for me, many thanks :)

**Comment by HakanL** [comment] 2021-10-07 12:57
> Works for new csproj based .NET Framework based projects (tested with dotnet publish) . Does not work for old style ASP.NET Framework projects... The files of wkhtmltox are copied flat into $publish folder but not into $publish/bin/runtimes/.../... where we would expect them. Sorry...

Not sure what the fix is for that, or if it's even possible.

**Comment by mrblumi** [comment] 2021-10-07 13:33
Well, this definitively fixes the bug i described in the initial statement of this issue.

But old ASP projects are still broken and one has to mess around with the build config to get this working. This was the only way i found to get the native dlls published into the correct location...
Not to mention that old style csrpoj is a mess in generall :D

**Comment by nickalbrecht** [comment] 2021-11-23 23:48
Not sure if my problem is the same issue or not (#61, I closed it when I THOUGHT I had fixed it, then found this issue), but I'm hitting a similar issue/symptom. When publishing (`dotnet publish`), I'm not getting the runtimes folder.
In my case (after MUCH trial and error), it seems to be related to RuntimeIdentifier? If I leave out the RuntimeIdentifier, then I get all of the runtimes when I publish, which is overkill, and bloats my publish file's size. My webapp app only runs on Windows. So I specify win-x64 as my runtime identifier. But as soon as I do that, the runtimes folder disappears from the publish output. I do see a `wkhtmltox.dll` in the root folder with all the other dependencies, but the file's size seems to only matches the x86 version? Actually, looks like that dll is _always_ there, even when I don't specify a runtime identifier. Is that supposed to be there at all? What's it for? However even if that's the correct file, it won't load it because the attributes in the `ModuleFactory.cs` file are hardcoded to only look in the `runtimes` folder.

Steps to reproduce

1. `dotnet new console Test`
2. `dotnet add package Haukcode.WkHtmlToPdfDotNet`
3. `dotnet publish --runtime-identifier win-x64 --self-contained false`

**Comment by nickalbrecht** [comment] 2021-11-24 00:04
This looks promising

https://stackoverflow.com/questions/40104838/automatic-native-and-managed-dlls-extracting-from-nuget-package

**Comment by HakanL** [comment] 2021-11-24 14:38
@nickalbrecht Hmm, no, there shouldn't be a file in the root, don't know where that's coming from. It may be some of the attempts to solve this issue, we do have some Nuget-related commits.

**Comment by HakanL** [comment] 2021-11-24 19:16
@nickalbrecht I think the latest version has this resolved. I've also added some test projects in the main solution to test the various platforms. It works for me in .NET 4.6.1, .NET 4.7.1, .NET 4.8, .NET Core 3.1, .NET 5, .NET 6 and also .NET 4.7.1 in the old csproj format.
@nickalbrecht and @mrblumi Can you please try version 1.5.64 to see if these issues are resolved?

**Comment by nickalbrecht** [comment] 2021-11-24 19:52
I just tried it using the same repro steps I had above, it grabbed `1.5.66` which I'm guessing is you still trying to fix things. It does include a `runtimes` folder now no matter what I do, but it also included `wkhtmltox.dll` in the root folder with all the other DLLs (if I specify a runtime), which appeared to be the correct file size for the given runtime. I checked it for both `win-x64` and `win-x86`, and it was the correct file size in both cases. I'm guessing that when specifying a specific runtime (either as a publish argument or just in the csproj file), it would forgo the nested runtimes folder and just copy the contents to the root bin folder. And when you don't specify a runtime, it leaves the resources inside of the `runtimes` folder.
So with `1.5.66`, if I specify `win-x64`, I'm seeing the correct file in the root folder, though, I know it won't be used, because the `ModuleFactory` has its DllImport attribute hardcoded to only look at the `runtimes` folder.

Would it be better to allow the `runtimes` folder to be excluded (as it seemed to be automatically originally, when an exact runtime is specified), and instead have `ModuleFactory` gracefully failover to looking for the dll in either the root folder (which should theoretically always be the right version, or nested in the `runtimes` folder?

**Comment by nickalbrecht** [comment] 2021-11-24 20:08
If it helps, when I used to use the DinkHtmlToPdf package (granted, this is on windows), I didn't load the wkhtmltox.dll directly via DllImport, so I didn't have to hardcode the path. Instead, I loaded it using this

```csharp
internal static class NativeMethods
{
    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true, EntryPoint = "LoadLibrary")]
    internal static extern IntPtr LoadLibrary(string libname);
}
```

```csharp
var ptr = NativeMethods.LoadLibrary(path);
if (ptr == IntPtr.Zero)
{
    throw new Exception($"Error loading {path} (ErrorCode: {Marshal.GetLastWin32Error()})");
}
```

**Comment by HakanL** [comment] 2021-11-24 22:00
> If it helps, when I used to use the DinkHtmlToPdf package (granted, this is on windows), I didn't load the wkhtmltox.dll directly via DllImport, so I didn't have to hardcode the path. Instead, I loaded it using this
> 
> ```cs
> internal static class NativeMethods
> {
>     [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true, EntryPoint = "LoadLibrary")]
>     internal static extern IntPtr LoadLibrary(string libname);
> }
> ```
> 
> ```cs
> var ptr = NativeMethods.LoadLibrary(path);
> if (ptr == IntPtr.Zero)
> {
>     throw new Exception($"Error loading {path} (ErrorCode: {Marshal.GetLastWin32Error()})");
> }
> ```

The issue is/was that NativeMethods.LoadLibrary is not available in .NET Core (now I think it's been added in .NET Core 3.0, so it may be an option now, but I forked Dink when it was .NET Core 2.0 and it wasn't available). And we have to make sure all this works in Windows, Mac and Linux/docker. But I'm open to rewrite it, but at the moment I don't have the time to spend to rewrite that part, but I'm happy to accept a PR, hint hint :)

**Comment by HakanL** [comment] 2021-11-24 22:04
If there is a way to exclude the runtimes folder when doing publish that would be good, but for the portable publish the recommended way (going off memory here) is to have the runtimes folder for native libraries. I think I had the initial load code in the ModuleFactory to cover that scenario (when the dll is in the root), but at least running it from VS it seems to work for all the different platforms right now.

**Comment by HakanL** [comment] 2022-05-16 05:33
I've tested the latest version with all the various client projects and they all seem to work. I'm closing this issue, feel free to re-open if anything related is still broken.

**Closed by HakanL** 2022-05-16 05:33 UTC
Labels: bug, help wanted
