### ISSUE TITLE
If I run my project out of Visual Studio 2019...

### ISSUE THREAD

**Issue by Paul-SB** [HakanL/WkHtmlToPdf-DotNet#67] opened 2021-12-21 14:27 UTC
When I start my project from Visual Studio, converting HTML to PDF works. As soon as I publish it and install the setup the conversion does not work anymore - unfortunately without any error message. At which point do the runtimes 
WkHtmlToPdf have to be located?

**Comment by HakanL** [comment] 2021-12-21 22:58
What .NET framework are you publishing for? See if you publish/run it in debug to see if there are any errors that can guide you to figure out what the issue is. Basically you should have the native binaries as part of the published folder.

**Comment by Paul-SB** [comment] 2021-12-22 07:46
I use .NET 4.7.2
In my published folder I see only WkHtmlToPdfDotNet.dll.deploy.

**Comment by Paul-SB** [comment] 2021-12-22 10:08
Is there a way to display the path to the runtimes during runtime

**Comment by Paul-SB** [comment] 2021-12-22 13:11
The solution for me was to add the following to the *.csproj or *.vbproj file:   
<ItemGroup>
    <Content Include="runtimes\**\*.*">
      <CopyToOutputDirectory>Always<//CopyToOutputDirectory>.
    </Content>
  </ItemGroup>

First, I copied the "runtimes" folder into the project directory.

**Comment by HakanL** [comment] 2021-12-22 14:51
Yeah this is a duplicate of #39, we don't have a good solution to support publish in the old .NET Framework at the moment.

**Closed by HakanL** 2021-12-22 14:51 UTC
